"use client";

import { FormEvent, useEffect, useState } from "react";
import { getSession } from "@/components/AuthGate";

type User = { id: string; username: string; name: string; role: "admin" | "school" | "battalion" | "company"; unitId?: string; password?: string; currentPassword?: string };
type Unit = { id: string; nameDaiDoi?: string; nameTieuDoan?: string };
const API = "http://localhost:3001";
const roleName = { admin: "Admin", school: "Nhà trường", battalion: "Chỉ huy Tiểu đoàn", company: "Chỉ huy Đại đội" };

export default function ProfilePage() {
  const [user, setUser] = useState<User | null>(() => getSession()); const [units, setUnits] = useState<Unit[]>([]); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [showCurrent, setShowCurrent] = useState(false); const [showNew, setShowNew] = useState(false); const [showSaved, setShowSaved] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([fetch(`${API}/auth/me`), fetch(`${API}/daiDoi`), fetch(`${API}/tieuDoan`)]).then(async ([me, companies, battalions]) => { if (me.ok) setUser(await me.json()); const [nextCompanies, nextBattalions] = await Promise.all([companies.ok ? companies.json() : [], battalions.ok ? battalions.json() : []]); setUnits([...(Array.isArray(nextCompanies) ? nextCompanies : []), ...(Array.isArray(nextBattalions) ? nextBattalions : [])]); if (!me.ok && !getSession()) setError("Không thể tải thông tin tài khoản."); }).catch(() => { if (!getSession()) setError("Không thể tải thông tin tài khoản."); }); }, []);
  const changePassword = async (event: FormEvent) => { event.preventDefault(); setError(""); setMessage(""); if (newPassword !== confirmPassword) return setError("Xác nhận mật khẩu mới chưa khớp."); setSaving(true); try { const response = await fetch(`${API}/auth/change-password`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword, newPassword }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Không thể đổi mật khẩu"); const session = getSession(); if (session) localStorage.setItem("student_session", JSON.stringify({ ...session, currentPassword: newPassword })); setUser((current) => current ? { ...current, password: newPassword, currentPassword: newPassword } : current); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); setMessage("Đã đổi mật khẩu thành công."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể đổi mật khẩu."); } finally { setSaving(false); } };
  const scope = user?.role === "company" ? units.find((unit) => unit.id === user.unitId)?.nameDaiDoi || user.unitId : user?.role === "battalion" ? units.find((unit) => unit.id === user.unitId)?.nameTieuDoan || user.unitId : "Toàn hệ thống";
  const savedPassword = user?.password || user?.currentPassword;
  return <div className="page-shell max-w-4xl space-y-5"><header className="rounded-3xl bg-gradient-to-br from-slate-700 to-blue-800 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-100">Tài khoản cá nhân</p><h1 className="mt-2 text-2xl font-bold">Thông tin của tôi</h1><p className="mt-2 text-sm text-blue-100">Bạn chỉ có thể xem thông tin và thay đổi mật khẩu của chính mình.</p></header>{error && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}<section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Thông tin cá nhân</h2>{user ? <dl className="mt-4 grid gap-4 sm:grid-cols-2"><Info label="Họ tên" value={user.name} /><Info label="Tên đăng nhập" value={user.username} /><Info label="Vai trò" value={roleName[user.role]} /><Info label="Phạm vi quản lý" value={scope || "Chưa gán"} /><div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Mật khẩu hiện tại</dt><dd className="mt-1 flex items-center justify-between gap-3 font-medium text-slate-900"><span>{savedPassword ? showSaved ? savedPassword : "••••••••" : "Hãy đăng xuất và đăng nhập lại"}</span>{savedPassword && <button type="button" onClick={() => setShowSaved((current) => !current)} className="text-xs font-semibold text-blue-700">{showSaved ? "Ẩn" : "Hiện"}</button>}</dd></div></dl> : <p className="mt-4 text-sm text-slate-500">Đang tải thông tin...</p>}</section><form onSubmit={changePassword} className="space-y-4 rounded-3xl border bg-white p-5 shadow-sm"><div><h2 className="text-lg font-bold">Đổi mật khẩu</h2><p className="mt-1 text-sm text-slate-500">Nhập mật khẩu hiện tại, sau đó đặt mật khẩu mới.</p></div><PasswordField label="Mật khẩu hiện tại" value={currentPassword} setValue={setCurrentPassword} show={showCurrent} setShow={setShowCurrent} /><PasswordField label="Mật khẩu mới" value={newPassword} setValue={setNewPassword} show={showNew} setShow={setShowNew} /><label className="field-label">Xác nhận mật khẩu mới<input required minLength={4} type={showNew ? "text" : "password"} value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} className="field-control mt-1" /></label><button disabled={saving} className="rounded-xl bg-blue-700 px-5 py-2.5 font-semibold text-white disabled:opacity-60">{saving ? "Đang cập nhật..." : "Cập nhật mật khẩu"}</button></form></div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 font-medium text-slate-900">{value}</dd></div>; }
function PasswordField({ label, value, setValue, show, setShow }: { label: string; value: string; setValue: (value: string) => void; show: boolean; setShow: (value: boolean) => void }) { return <label className="field-label">{label}<div className="relative mt-1"><input required minLength={4} type={show ? "text" : "password"} value={value} onChange={(event) => setValue(event.target.value)} className="field-control w-full pr-16" /><button type="button" onClick={() => setShow(!show)} className="absolute inset-y-0 right-1 rounded-lg px-3 text-xs font-semibold text-blue-700">{show ? "Ẩn" : "Hiện"}</button></div></label>; }
