"use client";

import { type FormEvent, useMemo, useState } from "react";
import { emptyAccount, type AccountForm, type Battalion, type Company, type ManagedUser, roles } from "@/components/permission-types";

type Props = { users: ManagedUser[]; battalions: Battalion[]; companies: Company[]; currentUserId?: string; saving: boolean; onCreate: (form: AccountForm) => Promise<boolean>; onUpdate: (user: ManagedUser, form: AccountForm) => Promise<boolean>; onToggleActive: (user: ManagedUser) => void };
export default function AccountManagement({ users, battalions, companies, currentUserId, saving, onCreate, onUpdate, onToggleActive }: Props) {
  const [account, setAccount] = useState<AccountForm>(emptyAccount); const [editing, setEditing] = useState<ManagedUser | null>(null); const [showNewPassword, setShowNewPassword] = useState(false);
  const unitName = (user: ManagedUser) => user.role === "company" ? companies.find((item) => item.id === user.unitId)?.nameDaiDoi || "Chưa gán" : user.role === "battalion" ? battalions.find((item) => item.id === user.unitId)?.nameTieuDoan || "Chưa gán" : "Toàn hệ thống";
  const submit = async (event: FormEvent) => { event.preventDefault(); if (await onCreate(account)) { setAccount(emptyAccount); setShowNewPassword(false); } };
  return <div className="space-y-5"><section className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-900">Tạo tài khoản mới</h2><p className="mt-1 text-sm text-slate-500">Chỉ huy phải được gán đúng đơn vị; Nhà trường và Admin quản lý toàn hệ thống.</p><AccountFields form={account} setForm={setAccount} battalions={battalions} companies={companies} showPassword={showNewPassword} setShowPassword={setShowNewPassword} required /><button disabled={saving} className="mt-4 rounded-xl bg-sky-600 px-4 py-3 font-semibold text-white disabled:opacity-60">Tạo tài khoản</button></form>
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-lg font-bold text-slate-900">Tài khoản người dùng</h2><p className="mt-1 text-sm text-slate-500">Sửa thông tin, đổi mật khẩu hoặc khoá/mở tài khoản.</p></div><div className="overflow-auto"><table className="min-w-[680px] w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3">Tài khoản</th><th className="px-4 py-3">Vai trò</th><th className="px-4 py-3">Phạm vi quản lý</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3" /></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-t"><td className="px-4 py-3"><b>{user.name}</b><span className="block text-xs text-slate-500">{user.username}</span></td><td className="px-4 py-3">{roles.find((role) => role.id === user.role)?.label}</td><td className="px-4 py-3">{unitName(user)}</td><td className="px-4 py-3">{user.active ? <span className="text-emerald-700">Đang hoạt động</span> : <span className="text-slate-500">Đã khóa</span>}</td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={() => setEditing(user)} className="rounded-lg border px-3 py-1.5 font-medium text-sky-700">Chỉnh sửa</button><button disabled={user.id === currentUserId} onClick={() => onToggleActive(user)} className="rounded-lg border px-3 py-1.5 font-medium text-slate-700 disabled:opacity-40">{user.active ? "Khóa" : "Mở"}</button></div></td></tr>)}{!users.length && <tr><td colSpan={5} className="p-8 text-center text-slate-500">Chưa có tài khoản.</td></tr>}</tbody></table></div></div></section>{editing && <EditAccount user={editing} battalions={battalions} companies={companies} saving={saving} onClose={() => setEditing(null)} onSave={(form) => onUpdate(editing, form)} />}</div>;
}
function AccountFields({ form, setForm, battalions, companies, showPassword, setShowPassword, required = false }: { form: AccountForm; setForm: (form: AccountForm) => void; battalions: Battalion[]; companies: Company[]; showPassword: boolean; setShowPassword: (value: boolean) => void; required?: boolean }) { const availableCompanies = useMemo(() => form.role === "company" ? companies : [], [companies, form.role]); return <div className="mt-4 grid gap-4"><label className="field-label">Họ tên<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="field-control mt-1" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="field-label">Tên đăng nhập<input required value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} className="field-control mt-1" /></label><label className="field-label">{required ? "Mật khẩu" : "Mật khẩu mới (tùy chọn)"}<div className="relative mt-1"><input required={required} minLength={4} type={showPassword ? "text" : "password"} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="field-control w-full pr-16" /><button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute inset-y-0 right-1 rounded-lg px-3 text-xs font-semibold text-sky-700">{showPassword ? "Ẩn" : "Hiện"}</button></div></label></div><label className="field-label">Vai trò<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as AccountForm["role"], unitId: "" })} className="field-control mt-1">{roles.map((role) => <option key={role.id} value={role.id}>{role.label}</option>)}</select></label>{form.role === "battalion" && <label className="field-label">Tiểu đoàn quản lý<select required value={form.unitId} onChange={(event) => setForm({ ...form, unitId: event.target.value })} className="field-control mt-1"><option value="">-- Chọn Tiểu đoàn --</option>{battalions.map((item) => <option key={item.id} value={item.id}>{item.nameTieuDoan}</option>)}</select></label>}{form.role === "company" && <label className="field-label">Đại đội quản lý<select required value={form.unitId} onChange={(event) => setForm({ ...form, unitId: event.target.value })} className="field-control mt-1"><option value="">-- Chọn Đại đội --</option>{availableCompanies.map((item) => <option key={item.id} value={item.id}>{item.nameDaiDoi}</option>)}</select></label>}</div>; }
function EditAccount({ user, battalions, companies, saving, onClose, onSave }: { user: ManagedUser; battalions: Battalion[]; companies: Company[]; saving: boolean; onClose: () => void; onSave: (form: AccountForm) => Promise<boolean> }) { const [form, setForm] = useState<AccountForm>({ name: user.name, username: user.username, password: "", role: user.role, unitId: user.unitId || "" }); const [showPassword, setShowPassword] = useState(false); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4" onClick={onClose}><form onSubmit={async (event) => { event.preventDefault(); if (await onSave(form)) onClose(); }} onClick={(event) => event.stopPropagation()} className="w-full max-w-xl rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold">Chỉnh sửa tài khoản</h2><p className="mt-1 text-sm text-slate-500">Để trống mật khẩu nếu không muốn thay đổi.</p></div><button type="button" onClick={onClose} className="text-xl text-slate-500">×</button></div><AccountFields form={form} setForm={setForm} battalions={battalions} companies={companies} showPassword={showPassword} setShowPassword={setShowPassword} /><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2">Hủy</button><button disabled={saving} className="rounded-xl bg-sky-600 px-4 py-2 font-semibold text-white disabled:opacity-60">Lưu thay đổi</button></div></form></div>; }
