/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import { useEffect, useState } from "react";
import { getSession } from "@/components/AuthGate";
import AccountManagement from "@/components/AccountManagement";
import RolePermissionManagement from "@/components/RolePermissionManagement";
import { type AccountForm, type Battalion, type Company, type ManagedUser, type Permission, type Role } from "@/components/permission-types";

const API = "http://localhost:3001";
type Section = "accounts" | "roles";

export default function PermissionsPage() {
  const [permissions, setPermissions] = useState<Permission[]>([]); const [users, setUsers] = useState<ManagedUser[]>([]); const [battalions, setBattalions] = useState<Battalion[]>([]); const [companies, setCompanies] = useState<Company[]>([]); const [draft, setDraft] = useState<Record<string, Role[]>>({}); const [section, setSection] = useState<Section>("accounts"); const [error, setError] = useState(""); const [saved, setSaved] = useState(""); const [saving, setSaving] = useState(false);
  const session = getSession(); const isAdmin = session?.role === "admin";
  const load = async () => { try { setError(""); const [permissionRes, usersRes, battalionRes, companyRes] = await Promise.all([fetch(`${API}/permissionCatalog`), fetch(`${API}/users`), fetch(`${API}/tieuDoan`), fetch(`${API}/daiDoi`)]); if (!permissionRes.ok || !usersRes.ok) throw new Error(); const nextPermissions = await permissionRes.json(); const nextUsers = await usersRes.json(); const nextBattalions = battalionRes.ok ? await battalionRes.json() : []; const nextCompanies = companyRes.ok ? await companyRes.json() : []; setPermissions(Array.isArray(nextPermissions) ? nextPermissions : []); setUsers(Array.isArray(nextUsers) ? nextUsers : []); setBattalions(Array.isArray(nextBattalions) ? nextBattalions : []); setCompanies(Array.isArray(nextCompanies) ? nextCompanies : []); const map: Record<string, Role[]> = {}; (Array.isArray(nextPermissions) ? nextPermissions : []).forEach((item: Permission) => { map[item.id] = item.roles || []; }); setDraft(map); } catch { setError("Không thể tải dữ liệu phân quyền."); } };
  useEffect(() => { if (isAdmin) void load(); }, [isAdmin]);
  const togglePermission = (permissionId: string, role: Role) => setDraft((previous) => ({ ...previous, [permissionId]: (previous[permissionId] || []).includes(role) ? previous[permissionId].filter((item) => item !== role) : [...(previous[permissionId] || []), role] }));
  const savePermissions = async () => { setSaving(true); setError(""); try { const results = await Promise.all(permissions.map((permission) => fetch(`${API}/permissionCatalog/${permission.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ roles: draft[permission.id] || [] }) }))); if (results.some((result) => !result.ok)) throw new Error(); await load(); setSaved("Đã lưu quyền chức năng. Các tài khoản cùng vai trò được cập nhật đồng nhất."); } catch { setError("Không thể lưu phân quyền."); } finally { setSaving(false); } };
  const createAccount = async (form: AccountForm) => { setSaving(true); setError(""); try { const response = await fetch(`${API}/users`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Không thể tạo tài khoản"); await load(); setSaved(`Đã tạo tài khoản ${data.username}.`); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể tạo tài khoản."); return false; } finally { setSaving(false); } };
  const updateAccount = async (user: ManagedUser, form: AccountForm) => { setSaving(true); setError(""); try { const payload = { name: form.name, username: form.username, role: form.role, unitId: form.unitId, ...(form.password ? { password: form.password } : {}) }; const response = await fetch(`${API}/users/${user.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Không thể cập nhật tài khoản"); await load(); setSaved(`Đã cập nhật tài khoản ${data.username}.`); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể cập nhật tài khoản."); return false; } finally { setSaving(false); } };
  const toggleActive = async (user: ManagedUser) => { const response = await fetch(`${API}/users/${user.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...user, active: !user.active }) }); if (!response.ok) { const data = await response.json(); setError(data.error || "Không thể cập nhật tài khoản."); return; } await load(); setSaved(`Đã ${user.active ? "khóa" : "mở"} tài khoản ${user.username}.`); };
  if (!isAdmin) return <div className="min-h-screen bg-slate-100 p-6"><div className="mx-auto max-w-2xl rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700 shadow-sm">Chỉ Admin mới được quản lý chức năng và tài khoản.</div></div>;
  return <div className="min-h-screen bg-slate-100 p-4 md:p-6"><div className="mx-auto max-w-7xl space-y-5"><header className="rounded-2xl border border-slate-200 bg-gradient-to-r from-sky-600 to-indigo-700 p-5 text-white shadow-lg"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-sky-100">Phân quyền hệ thống</p><h1 className="mt-2 text-2xl font-bold">Quản lý tài khoản & quyền chức năng</h1><p className="mt-1 text-sm text-sky-100">Tách riêng tài khoản người dùng và cấu hình quyền để thao tác gọn hơn.</p></header>{error && <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{saved && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{saved}</div>}<nav className="flex flex-wrap gap-1 rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm"><button onClick={() => setSection("accounts")} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${section === "accounts" ? "bg-sky-600 text-white" : "text-slate-600 hover:bg-slate-100"}`}>Quản lý tài khoản <span className="ml-1 rounded-full bg-white/20 px-2 py-0.5 text-xs">{users.length}</span></button><button onClick={() => setSection("roles")} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${section === "roles" ? "bg-sky-600 text-white" : "text-slate-600 hover:bg-slate-100"}`}>Vai trò & quyền chức năng <span className="ml-1 rounded-full bg-white/20 px-2 py-0.5 text-xs">{permissions.length}</span></button></nav>{section === "accounts" ? <AccountManagement users={users} battalions={battalions} companies={companies} currentUserId={session?.id} saving={saving} onCreate={createAccount} onUpdate={updateAccount} onToggleActive={toggleActive} /> : <RolePermissionManagement permissions={permissions} draft={draft} saving={saving} onToggle={togglePermission} onSave={() => void savePermissions()} />}<div className="rounded-2xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900"><b>Phạm vi dữ liệu:</b> Chỉ huy Đại đội chỉ xem và sửa học viên, lớp thuộc Đại đội được gán. Chỉ huy Tiểu đoàn chỉ quản lý các Đại đội trực thuộc Tiểu đoàn được gán. Nhà trường và Admin quản lý toàn bộ dữ liệu.</div></div></div>;
}
